In [ ]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arry_1D = np.array([10,20,30,40,50])

In [5]:
arry_1D

array([10, 20, 30, 40, 50])

In [6]:
array_2D = np.array([[1,2,3],[4,5,6]])

In [7]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array_2D.shape

(2, 3)

In [10]:
array_2D.dtype

dtype('int32')

NumPy arrays provide a more efficient, faster, and powerful way to work with numerical data compared to Python lists, especially when dealing with large datasets or complex mathematical operations.

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[6,7,9]]])

In [16]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [6, 7, 9]]])

In [18]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])